hello:
	echo "Hello, World"

blah: blah.o
	cc blah.o -o blah # Runs third

blah.o: blah.c
	cc -c blah.c -o blah.o # Runs second

# Typically blah.c would already exist, but I want to limit any additional required files
blah.c:
	echo "int main() { return 0; }" > blah.c # Runs first

clean:
	ls | grep -E -v "Makefile|*.c" |xargs rm -f 
